export const productos = [
  {
    id:'1',
    title:'Textil 1',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img1.png', 'img/img2.png'],
    categ:'textil',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'2',
    title:'Textil 2',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img2.png', 'img/img1.png'],
    categ:'textil',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'3',
    title:'Textil 3',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img1.png', 'img/img2.png'],
    categ:'textil',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'4',
    title:'Caja de Primeros Auxilios',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img2.png', 'img/img1.png'],
    categ:'natural',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'5',
    title:'Caja de Emergencia',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img1.png', 'img/img2.png'],
    categ:'natural',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'6',
    title:'Botiquín Natural',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'natural',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'7',
    title:'Vela Insecticida',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img3.png', 'img/img4.png'],
    categ:'natural',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'8',
    title:'Almohadillas Antipolillas',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'natural',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'9',
    title:'Kutxa Tarjetas',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img3.png', 'img/img4.png'],
    categ:'guagua',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'10',
    title:'Kutxa Títeres',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img6.png', 'img/img5.png'],
    categ:'guagua',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'11',
    title:'Kutxa Atrapasueños',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img5.png', 'img/img6.png'],
    categ:'guagua',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'12',
    title:'Kutxa Divertida',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img6.png', 'img/img5.png'],
    categ:'guagua',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'13',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    title:'Kutxa Mitológica',
    button:'Agregar',
    img:['img/img5.png', 'img/img6.png'],
    categ:'guagua',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'14',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    title:'Kutxa Navideña',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'guagua',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'15',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    title:'Kutxa Germinación',
    button:'Agregar',
    img:['img/img3.png', 'img/img4.png'],
    categ:'guagua',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'16',
    title:'Kutxa Primeras Puntadas',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'guagua',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'17',
    title:'Kutxa Vacaciones',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img3.png', 'img/img4.png'],
    categ:'guagua',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'18',
    title:'Aceite 1',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'natural',
    filtro:'aceites',
    precio: '100',
  },
  {
    id:'19',
    title:'Aceite 2',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img1.png', 'img/img2.png'],
    categ:'natural',
    filtro:'aceites',
    precio: '100',
  },
  {
    id:'20',
    title:'Aceite 3',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img2.png', 'img/img1.png'],
    categ:'natural',
    filtro:'aceites',
    precio: '100',
  },
  {
    id:'21',
    title:'Aceite 4',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img1.png', 'img/img2.png'],
    categ:'natural',
    filtro:'aceites',
    precio: '100',
  },
  {
    id:'22',
    title:'Aceite 5',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img2.png', 'img/img1.png'],
    categ:'natural',
    filtro:'aceites',
    precio: '100',
  },
  {
    id:'23',
    text:'Componente: Erythroxylum coca. Acción: analgésico, calmante, antiflatulento, astringente, agente de limpieza de la sangre, adelgazante, inhibe la sensación de hambre y sed, equilibra los efectos del cansancio y el estrés. Preserva la dentadura y la cavidad bucal, contra la estomatitis, la llagas. Contra la osteoporosis, tiene más calcio que la leche y tanto fósforo como el pescado. Se recomienda en la hiperactividad y para la bulimia y la obesidad, controla el apetito sin desnutrir. Aumenta la resistencia física, mejora el funcionamiento del hígado, regula el colesterol y los triglicéridos. En gargarismos es anestésico local, alivia dolores de la boca y la garganta.',
    title:'T Coca',
    button:'Agregar',
    img:['img/img3.png', 'img/img4.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'24',
    title:'CB',
    text:'Componentes: Carqueja y Boldo. Acción: Digestivo, hepatoprotector, antiespasmódico, depurativo, estimulante. Combate afecciones del hígado y el estómago, litiasis biliar, ictericia, insuficiencia de la secreción biliar, cirrosis hepática, cirrosis atrófica, cólicos hepáticos, tónico- estimulante de la función gástrica. Diurético, depurativo, para borrar las manchas de la cara, en forunculosis rebeldes, urticaria, abcesos, erupciones y granos. Además, se indica en el reumatismo, los dolores reumáticos, espasmos de la musculatura lisa y la excitabilidad nerviosa.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'25',
    title:'HUTLE',
    text:'Componentes: Malva, Plantago maior, Carqueja y Caléndula. Acción: Combate las Hemorroides, úlceras, estreñimiento, el tránsito lento. Previene las úlceras y pólipos intestinales. Astringente, cicatrizante y vulnerario; eupéptico, digestivo, antiespasmódico, relajante estomacal. Indicado en problemas digestivos, flatulencias.',
    button:'Agregar',
    img:['img/img3.png', 'img/img4.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'26',
    title:'KM 13 hierbas',
    text:'Componentes: Sen hojas, té verde, ginkgo biloba, pasionaria flor, menta, ocimum basilicum, rosmarinus officinalis, Stevia Rebaudiana, cáscaras de naranja, cáscaras de manzana verde, coca, cannabis, Hipericum perforatum. Acción: Antioxidante, antidepresivo, favorece la concentración, la memoria, la atención y la motivación. Energizante, estimulante, revitalizante. Indicado en situaciones de exigencia de concentración, memoria, estudio. Estimula la irrigación cerebral, favorece la vista, el oído, previene el glaucoma y el estrés.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'27',
    title:'AD',
    text:'Componentes: coca, té verde, Lepidium sativum, Stevia Rebaudiana, Taraxacum officinale. Acción: Adelgazante natural, depurativo, diurético, no reduce el potasio, estimula el metabolismo, mejora la función del aparato urinario y de la vesícula biliar, regula el apetito, controla la ansiedad relacionada con la comida. Provoca adelgazamiento natural, no invasivo ni prohibitivo, no tiene contraindicaciones, no es laxante, indicado además para la digestión lenta.',
    button:'Agregar',
    img:['img/img5.png', 'img/img6.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'271',
    title:'DETAN',
    text:'Componentes: pasionaria, Hipericum Perforatum. Acción: Depresión, terrores nocturnos, ansiedad. Indicado también en casos de agotamiento, cansancio extremo, insomnio, pánico, desequilibrios y desbordes emocionales. Trastornos de la conducta.',
    button:'Agregar',
    img:['img/img6.png', 'img/img5.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'272',
    title:'DETAN-C',
    text:'Componentes: pasionaria, Hipericum Perforatum, Cannabis. Acción: Depresión, terrores nocturnos, ansiedad, pánico, dolores, fibromialgia. Cambios de humor, desgano, agotamiento, estrés post traumático.',
    button:'Agregar',
    img:['img/img5.png', 'img/img6.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'273',
    title:'PHADE 5 hierbas',
    text:'Componentes: geranio, menta, lavanda, manzanilla, pasionaria. Acción: Indicado para pesadillas, malhumor, cambios bruscos de humor, ansiedad, desequilibrios emocionales, estrés post traumático, desgano, menopausia, convulsiones, hipo o llanto incontrolable; tics nerviosos.',
    button:'Agregar',
    img:['img/img6.png', 'img/img5.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'274',
    title:'CBV 8 hierbas',
    text:'Componentes: malva, caléndula, kalanchoe, coca, Ocimum basilicum, carqueja, boldo, cardo mariano. Acción: Indicado en problemas de la vesícula y para cálculos biliares. Cirrosis crónica. Regenerador del hígado. Digestivo, hepatoprotector, antiespasmódico, depurativo, estimulante. Combate afecciones del hígado, litiasis biliar, ictericia, insuficiencia de la secreción biliar, cirrosis hepática, cirrosis atrófica, cólicos hepáticos, tónico- estimulante de la función gástrica.',
    button:'Agregar',
    img:['img/img5.png', 'img/img6.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'275',
    title:'CANHU',
    text:'Componentes: malva, manzanilla, plántago maior. Acción: Antiulceroso, antihemorroidal, antiflatulento, calmante de los nervios del estómago.',
    button:'Agregar',
    img:['img/img1.png', 'img/img2.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'276',
    title:'CANHU-A',
    text:'Componentes: malva, manzanilla, plántago, albahaca. Acción: Antiulceroso, antihemorroidal, antiespasmódico, calmante de los nervios del estómago, facilita la digestión, colabora en la limpieza de la vesícula.',
    button:'Agregar',
    img:['img/img2.png', 'img/img1.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'277',
    title:'CANHU-V',
    text:'Componentes: malva, manzanilla, plántago, castaño de Indias. Acción: Antiulceroso, antihemorroidal, colabora en el tratamiento de las várices, desinflamante, antiespasmódico, descongestivo, antineurálgico.',
    button:'Agregar',
    img:['img/img1.png', 'img/img2.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'278',
    title:'NIED 9 hierbas',
    text:'Componentes: manzanilla, valeriana, cedrón, melisa, menta, artemisa, cannabis, cáscaras de naranja, cáscaras de manzana verde. Acción: Indicado en nervios, insomnio, estrés y depresión, trastornos nerviosos, irritabilidad, vértigo, fobias, pánico. También en estados de desequilibrios emocionales, ansiedad, histeria, baja autoestima, esquizofrenia y paranoia. Relajante natural intenso.',
    button:'Agregar',
    img:['img/img2.png', 'img/img1.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'279',
    title:'COL 1',
    text:'Componentes: taraxacum officinale, té verde, albahaca, poleo. Acción: Combate la acumulación y depósito de las grasas. Disminuye la viscosidad sanguínea. Reduce el colesterol en sangre y estimula las funciones de drenaje, hepáticas y renales.',
    button:'Agregar',
    img:['img/img3.png', 'img/img4.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'280',
    title:'COL 2- 7 hierbas',
    text:'Componentes: geranio, ocimum basilicum, taraxacum officinale, manzanilla, stevia rebaudiana, cannabis, cáscaras de naranja y manzana. Acción: Combate la acumulación y depósito de las grasas. Disminuye la viscosidad sanguínea. Reduce el colesterol. Ayuda en estados nerviosos, de irritabilidad, baja autoestima, insomnio, estrés.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'281',
    title:'COL 3 -H',
    text:'Componentes: stevia rebaudiana, té verde, lepidium sativum, taraxacum officinale, hipericum perforatum. Acción: Combate la acumulación y depósito de las grasas. Disminuye la viscosidad sanguínea. Reduce el colesterol y los triglicéridos. Ayuda en trastornos nerviosos y estados depresivos.',
    button:'Agregar',
    img:['img/img3.png', 'img/img4.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'282',
    title:'COL 4- 7 hierbas',
    text:'Componentes: diente de león, stevia rebaudiana, lepidium sativum, hibiscus flor, té verde, palta hojas, equisetum. Acción: Reduce el colesterol alto. Combate el estreñimiento. Reduce los niveles de colesterol. Previene enfermedades cardíacas.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'283',
    title:'ABC+',
    text:'Componentes: Anacahuita, eucalipto, ambay, bugambilia, chañar y perilla, alcohol. Acción: Expectorante. Indicado en casos de asma, bronquitis, catarro, tos seca, alivia los síntomas de la sinusitis, la rinitis, las alergias, problemas respiratorios y la EPOC, previene la oclusión bronquial. Alivia las dificultades respiratorias, evita los ataques de asma. También actúa en todo tipo de afecciones alérgicas, como eczemas, dermatitis, prurito y urticaria.',
    button:'Agregar',
    img:['img/img5.png', 'img/img6.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'284',
    title:'TP',
    text:'Tintura para la piel. Componentes: Urtica dioica, caléndula, malva, geranio, plántago maior, alcohol. Acción: Fortalece, depura y mejora el aspecto de la piel. Elimina toxinas y suciedad, limpia los poros, barre impurezas, espinillas, granos y puntos negros, tonifica la piel. Previene el acné y el eczema, colabora con el tratamiento de las alergias y el enrojecimiento de la piel.',
    button:'Agregar',
    img:['img/img6.png', 'img/img5.png'],
    categ:'natural',
    filtro:'tinturas',
    precio: '100',
  },
  {
    id:'28',
    title:'Crema de coca',
    text:'Componentes: Aceite de Coca, cera de abejas. Acción: Se usa para aliviar dolores musculares, articulares, lumbalgias, neuralgias, golpes, alivia dolores muy fuertes en las articulaciones en el caso de la artritis, artrosis y reumatismo y gota. La coca fija la vitamina C. Es relajante articular y muscular, fortalece huesos y dientes, previene la osteoporosis. En la piel también es fuente de calcio, vitamina A, B, B12, magnesio y potasio.',
    button:'Agregar',
    img:['img/img5.png', 'img/img6.png'],
    categ:'natural',
    filtro:'cremas',
    precio: '100',
  },
  {
    id:'29',
    title:'Crema Óleo31+Can',
    text:'Componentes: Óleo 31, aceite de cannabis, cera de abejas. Acción: Calmante de dolores, desinflamante, descontracturante, vasodilatador, relajante muscular, previene el envejecimiento prematuro de los tejidos y la rigidez de los músculos y las articulaciones.',
    button:'Agregar',
    img:['img/img6.png', 'img/img5.png'],
    categ:'natural',
    filtro:'cremas',
    precio: '100',
  },
  {
    id:'30',
    title:'Crema CCAJ',
    text:'Componentes: Aceite de Consuelda, cannabis, Árnica Montana y Jarilla. Acción: Antiinflamatoria, antiespasmódica, calmante de dolores crónicos y fuertes en articulaciones, músculos, tendones y huesos. Activa la circulación de la sangre, alivia golpes, torceduras, esguinces, dolores post operatorios y post traumáticos. Revitaliza zonas entumecidas o faltas de sensibilidad, activa la irrigación sanguínea en las capas profundas de la piel. Mejora notablemente el aspecto de la piel de las manos, elimina manchas de sol, remueve impurezas. Colabora en el tratamiento de la artrosis en manos y pies y alivia los juanetes, ojos de gallo, uñas encarnadas. Es una aliada importante en el tratamiento del pie diabético.',
    button:'Agregar',
    img:['img/img1.png', 'img/img2.png'],
    categ:'natural',
    filtro:'cremas',
    precio: '100',
  },
  {
    id:'31',
    title:'Crema de Caléndula',
    text:'Componentes: Caléndula officinalis, cera de abejas. Acción: Antibacteriana, antibiótica, antiespasmódica, antiinflamatoria, antimicótica, antiparasitaria, antiséptica, cicatrizante, fungicida. Se aplica en casos de abcesos, acné, dermatitis del pañal, escaldaduras, picaduras de insectos, quemaduras, forúnculos, irritaciones cutáneas, escaras, úlceras de la piel. Colabora en tratamientos de úlceras varicosas y otras afecciones crónicas de la piel.',
    button:'Agregar',
    img:['img/img2.png', 'img/img1.png'],
    categ:'natural',
    filtro:'cremas',
    precio: '100',
  },
  {
    id:'32',
    title:'Crema COOL Expectorante',
    text:'Componentes: Aceite de tomillo y de eucaliptus, con chañar y alcanfor, cera de abejas, aceite de oliva. Acción: Indicada para combatir tos, resfríos, dolor de garganta, alivia estados gripales y afonías.',
    button:'Agregar',
    img:['img/img1.png', 'img/img2.png'],
    categ:'natural',
    filtro:'cremas',
    precio: '100',
  },
  {
    id:'321',
    title:'Crema de Malva',
    text:'Componentes: Aceite de malva, aceite de manzanilla, cera de abejas. Acción: Antiinflamatoria, antiséptica. Indicada para aliviar hemorroides, forúnculos, eczemas, úlceras, picaduras, quemaduras, heridas y llagas de la piel. Aplicada en el pecho es anticatarral, expectorante, alivia dolores de garganta, faringitis, bronquitis, tos y catarros. Colabora en la artritis, la gota, los dolores lumbares por su acción desinflamante.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'natural',
    filtro:'cremas',
    precio: '100',
  },
  {
    id:'33',
    title:'Canasta de Té para la Menopausia',
    text:'Contiene: Cimicífuga, equisetum, doradilla, melisa, menta, peperina, valeriana, pasionaria y cannabis. Alivia los sofocos y calores del climaterio. Los sofocos se presentan durante el día o la noche, pueden durar segundos o minutos (cinco o diez), persisten durante al menos cinco años y provocan fatiga física y mental e insomnio. Reduce el estrés, el nerviosismo y la ansiedad de comer. Colocar una cucharadita por taza, retirar al primer hervor, dejar descansar. Beber una taza antes de acostarse.',
    button:'Agregar',
    img:['img/img3.png', 'img/img4.png'],
    categ:'natural',
    filtro:'canastas',
    precio: '100',
  },
  {
    id:'34',
    title:'Canasta de Té para la Migraña',
    text:'Contiene: Tomillo, marcela, fumaria, menta piperita, verbena, coriandro, vira vira, valeriana, cáscaras de naranja dulce, manzanilla y cannabis. Desinflamatorio, descongestiona y alivia dolores de cabeza. Reduce el estrés y la frecuencia de las migrañas, induce a un sueño regular. Usar una cucharadita de hierba por taza, se puede preparar un litro e ir bebiendo durante el día, caliente o natural.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'natural',
    filtro:'canastas',
    precio: '100',
  },
  {
    id:'35',
    title:'Canasta de Té Sedante',
    text:'Contiene: valeriana, manzanilla, tilo, pasionaria, cannabis, salvia, menta, azahares, melisa, bugambilia. Reduce el estrés cotidiano, calma y relaja los músculos, tranquiliza y favorece el descanso a través de un sueño tranquilo, sin interrupciones. Prepararlo con una cucharadita de hierbas por taza de agua, retirar al primer hervor, endulzar con stevia líquida. Beber dos tazas, una después de las comidas.',
    button:'Agregar',
    img:['img/img3.png', 'img/img4.png'],
    categ:'natural',
    filtro:'canastas',
    precio: '100',
  },
  {
    id:'36',
    title:'Canasta de Té para niños',
    text:'Contiene: manzanilla, yerba del pollo, hinojo, aenethum, paico, cáscaras de naranja y manzana verde. Calma dolores estomacales, gases, diarreas leves y malestar por indigestión. Usar una cucharadita por taza, endulzar con miel y dar a beber una taza después de las comidas.',
    button:'Agregar',
    img:['img/img6.png', 'img/img5.png'],
    categ:'natural',
    filtro:'canastas',
    precio: '100',
  },
  {
    id:'37',
    title:'Canasta de Té Estimulante y Digestiva',
    text:'Contiene: Salvia, diente de león, melisa, poleo, cedrón, manzanilla, boldo, paico, cáscara de naranja dulce, tomillo, burrito, flores de bugambilia, caléndula, equisetum, menta, yerbabuena. Favorece la digestión, produce un efecto de bienestar y renueva energías. Calma dolores estomacales, estreñimiento y cólicos hepáticos. Regulariza el funcionamiento del sistema biliar y digestivo. Prepararlo con una cucharadita de hierbas por taza de agua, retirar al primer hervor, endulzar con stevia líquida. Beber dos tazas, una después de las comidas. Se puede poner también una cucharadita en el mate, antes de la yerba.',
    button:'Agregar',
    img:['img/img5.png', 'img/img6.png'],
    categ:'natural',
    filtro:'canastas',
    precio: '100',
  },
  {
    id:'38',
    title:'Almohadilla Terapeutica 6',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img6.png', 'img/img5.png'],
    categ:'natural',
    filtro:'almohadillas',
    precio: '100',
  },
  {
    id:'39',
    title:'Almohadilla Terapeutica 1',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img1.png', 'img/img2.png'],
    categ:'natural',
    filtro:'almohadillas',
    precio: '100',
  },
  {
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    id:'40',
    title:'Almohadilla Terapeutica 2',
    button:'Agregar',
    img:['img/img2.png', 'img/img1.png'],
    categ:'natural',
    filtro:'almohadillas',
    precio: '100',
  },
  {
    id:'41',
    title:'Almohadilla Terapeutica 3',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img1.png', 'img/img2.png'],
    categ:'natural',
    filtro:'almohadillas',
    precio: '100',
  },
  {
    id:'42',
    title:'Almohadilla Terapeutica 4',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'natural',
    filtro:'almohadillas',
    precio: '100',
  },
  {
    id:'43',
    title:'Almohadilla Terapeutica 5',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img3.png', 'img/img4.png'],
    categ:'natural',
    filtro:'almohadillas',
    precio: '100',
  },
  {
    id:'51',
    title:'Kutxa Mi Regalo',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img4.png', 'img/img3.png'],
    categ:'kutxa',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'52',
    title:'Kutxa Estudiantes',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img5.png', 'img/img6.png'],
    categ:'kutxa',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'53',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    title:'Kutxa  Novios',
    button:'Agregar',
    img:['img/img6.png', 'img/img5.png'],
    categ:'kutxa',
    filtro:'otros',
    precio: '100',
  },
  {
    id:'54',
    title:'Kutxa Bebé',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['img/img5.png', 'img/img6.png'],
    categ:'kutxa',
    filtro:'otros',
    precio: '100',
},
];

export const ofertas = [
{
  id: '99',
  title: "Oferta 1",
  text: "Descripcion y contenido de la oferta ",
  button: "Agregar",
  img:'img/img1.png',
  precio: '100',
},
{
  id: '98',
  title: "Oferta 2",
  text: "Descripcion y contenido de la oferta 2",
  button: "Comprar",
  img:'img/img2.png',
  precio: '100',
  },
{
  id: '97',
  title: "Oferta 3",
  text: "Descripcion y contenido de la oferta 3",
  button: "Se acaba!",
  img:'img/img3.png',
  precio: '100',
},
{
  id:'96',
  title: "Oferta 4",
  text: "Descripcion y contenido de la oferta 4",
  button: "Ultima unidad",
  img:'img/img4.png',
  precio: '100',
},
{
  id: '95',
  title: "Oferta 5",
  text: "Descripcion y contenido de la oferta 5",
  button: "Llevatelo!",
  img:'img/img5.png',
  precio: '100',
},
];

export const banner = [
{
  imgSrt: 'Oferta!',
  title: 'Nombre producto en oferta',
  text: 'Una pequeña descripcion de nuestra oferta.',
  img:'holder.js/20x20',
},
{
  imgSrt: 'Ultimo Lanzamiento!',
  title: 'Nombre del producto en lanzamiento',
  text: 'Una breve historia del ultimo lanzamiento.',
  img:'holder.js/20x20',
},
{
  imgSrt: 'Aprovecha antes que se termine!',
  title: 'Nombre del producto a vender',
  text: 'Una descripcion del producto que tenemos sobrante de stock.',
  img:'holder.js/20x20',
}];

export const contacto = [
  {
    nombre:'E-mail',
    link:'http://mail.google.com',
    img:'holder.js/20x20',
  },
  {
    nombre:'Facebook',
    link:'http://www.facebook.com',
    img:'holder.js/20x20',
  },
  {
    nombre:'Instagram',
    link:'http://www.instagram.com',
    img:'holder.js/20x20',
  },
  {
    nombre:'Twitter',
    link:'http://www.twitter.com',
    img:'holder.js/20x20',
  },
  {
    nombre:'Whatsapp',
    link:'https://api.whatsapp.com/send?phone=543544609044&text=Hola!%20Me%20interesa%20realizar%20una%20compra',
    img:'holder.js/20x20',
  },
];

export const mediosDePago = {
  banco: {
    banco: 'banco fulano',
    titular: 'Apellido, nombre',
    cuenta: '1234567890123',
    alias: 'alia.s.cbu',
    cbu: '1234567890123456789012',
    tipo: 'caja de ahorro',
  },
  uala: {
    titular: 'Apellido, nombre',
    alias: 'alias.uala',
    cbu: '1234567890123456789012',
  },
};

export const datosEnvio = [
];
