export const productos = [
  {
    id:'1',
    title:'Textil 1',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'textil',
    filtro:'otros',
  },
  {
    id:'2',
    title:'Textil 2',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'textil',
    filtro:'otros',
  },
  {
    id:'3',
    title:'Textil 3',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'textil',
    filtro:'otros',
  },
  {
    id:'4',
    title:'Caja de Primeros Auxilios',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'otros',
  },
  {
    id:'5',
    title:'Caja de Emergencia',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'otros',
  },
  {
    id:'6',
    title:'Botiquín Natural',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'otros',
  },
  {
    id:'7',
    title:'Vela Insecticida',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'otros',
  },
  {
    id:'8',
    title:'Almohadillas Antipolillas',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'otros',
  },
  {
    id:'9',
    title:'Kutxa Tarjetas',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'guagua',
    filtro:'otros',
  },
  {
    id:'10',
    title:'Kutxa Títeres',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'guagua',
    filtro:'otros',
  },
  {
    id:'11',
    title:'Kutxa Atrapasueños',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'guagua',
    filtro:'otros',
  },
  {
    id:'12',
    title:'Kutxa Divertida',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'guagua',
    filtro:'otros',
  },
  {
    id:'13',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    title:'Kutxa Mitológica',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'guagua',
    filtro:'otros',
  },
  {
    id:'14',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    title:'Kutxa Navideña',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'guagua',
    filtro:'otros',
  },
  {
    id:'15',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    title:'Kutxa Germinación',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'guagua',
    filtro:'otros',
  },
  {
    id:'16',
    title:'Kutxa Primeras Puntadas',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'guagua',
    filtro:'otros',
  },
  {
    id:'17',
    title:'Kutxa Vacaciones',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'guagua',
    filtro:'otros',
  },
  {
    id:'18',
    title:'Aceite 1',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'aceites',
  },
  {
    id:'19',
    title:'Aceite 2',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'aceites',
  },
  {
    id:'20',
    title:'Aceite 3',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'aceites',
  },
  {
    id:'21',
    title:'Aceite 4',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'aceites',
  },
  {
    id:'22',
    title:'Aceite 5',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'aceites',
  },
  {
    id:'23',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    title:'Tintura 1',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'tinturas',
  },
  {
    id:'24',
    title:'Tintura 2',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'tinturas',
  },
  {
    id:'25',
    title:'Tintura 3',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'tinturas',
  },
  {
    id:'26',
    title:'Tintura 4',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'tinturas',
  },
  {
    id:'27',
    title:'Tintura 5',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'tinturas',
  },
  {
    id:'28',
    title:'Crema 1',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'cremas',
  },
  {
    id:'29',
    title:'Crema 2',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'cremas',
  },
  {
    id:'30',
    title:'Crema 3',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'cremas',
  },
  {
    id:'31',
    title:'Crema 4',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'cremas',
  },
  {
    id:'32',
    title:'Crema 5',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'cremas',
  },
  {
    id:'33',
    title:'Canasta de Té 1',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'canastas',
  },
  {
    id:'34',
    title:'Canasta de Té 2',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'canastas',
  },
  {
    id:'35',
    title:'Canasta de Té 3',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'canastas',
  },
  {
    id:'36',
    title:'Canasta de Té 4',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'canastas',
  },
  {
    id:'37',
    title:'Canasta de Té 5',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'canastas',
  },
  {
    id:'38',
    title:'Almohadilla Terapeutica 6',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'almohadillas',
  },
  {
    id:'39',
    title:'Almohadilla Terapeutica 1',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'almohadillas',
  },
  {
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    id:'40',
    title:'Almohadilla Terapeutica 2',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'almohadillas',
  },
  {
    id:'41',
    title:'Almohadilla Terapeutica 3',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'almohadillas',
  },
  {
    id:'42',
    title:'Almohadilla Terapeutica 4',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'almohadillas',
  },
  {
    id:'43',
    title:'Almohadilla Terapeutica 5',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'natural',
    filtro:'almohadillas',
  },
  {
    id:'51',
    title:'Kutxa Mi Regalo',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'kutxa',
    filtro:'otros',
  },
  {
    id:'52',
    title:'Kutxa Estudiantes',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'kutxa',
    filtro:'otros',
  },
  {
    id:'53',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    title:'Kutxa  Novios',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'kutxa',
    filtro:'otros',
  },
  {
    id:'54',
    title:'Kutxa Bebé',
    text:'Una descripcion del producto. Esto puede ser detallado o un simple paneo general. Si entra puede ver mas.',
    button:'Agregar',
    img:['holder.js/100px180', 'holder.js/100px180'],
    categ:'kutxa',
    filtro:'otros',
  },
];

export const ofertas = [
{
  title: "Oferta 1",
  text: "Descripcion y contenido de la oferta ",
  button: "Agregar",
  img:'holder.js/100px180',
  },
{
  title: "Oferta 2",
  text: "Descripcion y contenido de la oferta 2",
  button: "Comprar",
  img:'holder.js/100px180',
  },
{
  title: "Oferta 3",
  text: "Descripcion y contenido de la oferta 3",
  button: "Se acaba!",
  img:'holder.js/100px180',
},
{
  title: "Oferta 4",
  text: "Descripcion y contenido de la oferta 4",
  button: "Ultima unidad",
  img:'holder.js/100px180',
},
{
  title: "Oferta 5",
  text: "Descripcion y contenido de la oferta 5",
  button: "Llevatelo!",
  img:'holder.js/100px180',
},
];

export const banner = [
{
  imgSrt: 'Oferta!',
  title: 'Nombre producto en oferta',
  text: 'Una pequeña descripcion de nuestra oferta.',
  img:'holder.js/20x20',
},
{
  imgSrt: 'Ultimo Lanzamiento!',
  title: 'Nombre del producto en lanzamiento',
  text: 'Una breve historia del ultimo lanzamiento.',
  img:'holder.js/20x20',
},
{
  imgSrt: 'Aprovecha antes que se termine!',
  title: 'Nombre del producto a vender',
  text: 'Una descripcion del producto que tenemos sobrante de stock.',
  img:'holder.js/20x20',
}];

export const contacto = [
  {
    nombre:'E-mail',
    link:'http://www.mail.google.com',
    img:'holder.js/20x20',
  },
  {
    nombre:'Facebook',
    link:'http://www.facebook.com',
    img:'holder.js/20x20',
  },
  {
    nombre:'Instagram',
    link:'http://www.instagram.com',
    img:'holder.js/20x20',
  },
  {
    nombre:'Twitter',
    link:'http://www.twitter.com',
    img:'holder.js/20x20',
  },
];

export const datosEnvio = [
];
